In [148]:
import numpy as np
import pandas as pd

In [149]:
df = pd.read_csv('loan_prediction.csv')

In [150]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [152]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [153]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [154]:
categorical_columns = ['Gender', 'Married', 'Dependents', 'Self_Employed']

In [155]:
for column in categorical_columns:
    df[column].fillna(df[column].mode()[0], inplace = True)

In [156]:
numerical_columns = ['LoanAmount','Loan_Amount_Term', 'Credit_History']

In [157]:
for col in numerical_columns:
    df[col].fillna(df[col].mean(), inplace = True)

In [158]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [159]:
df.drop(columns=['Loan_ID'], inplace = True)

In [160]:
df

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0  146.412162             360.0             1.0   
1               1508.0  128.000000             360.0             1.0   
2                  0.0   66.000000             360.0             1.0   
3               2358.0  120.000000             360.0             1.0   
4                  0.0  141.000000             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0   71.000000             360.0             1.0   
610                0.0   40.000000             180.0             1.0   
611              240.0  253.000000             360.0             1.0   
612                0.0  187.000000             360.0             1.0   
613                0.0  133.000000             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [161]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [162]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [163]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [164]:
X[0]

array([0.0, 1.0, 'No', '0', 'Graduate', 'No', 5849, 0.0,
       146.41216216216216, 360.0, 1.0, 'Urban'], dtype=object)

In [165]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [2])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [166]:
X[0]

array([1.0, 0.0, 0.0, 1.0, '0', 'Graduate', 'No', 5849, 0.0,
       146.41216216216216, 360.0, 1.0, 'Urban'], dtype=object)

In [167]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [4])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [168]:
X[0]

array([1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 'Graduate', 'No', 5849,
       0.0, 146.41216216216216, 360.0, 1.0, 'Urban'], dtype=object)

In [169]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [8])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [170]:
X[0]

array([1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 'No', 5849, 0.0,
       146.41216216216216, 360.0, 1.0, 'Urban'], dtype=object)

In [171]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [10])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [172]:
X[0]

array([1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 5849,
       0.0, 146.41216216216216, 360.0, 1.0, 'Urban'], dtype=object)

In [173]:
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [17])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [174]:
X[0]

array([0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 1.0, 5849, 0.0, 146.41216216216216, 360.0, 1.0], dtype=object)

In [175]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [176]:
y = le.fit_transform(y)

In [177]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [178]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [179]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [180]:
X_train[:, 15:] = scaler.fit_transform(X_train[:, 15:])
X_test[:, 15:] = scaler.transform(X_test[:, 15:])

In [181]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

In [182]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [183]:
predictions = classifier.predict(X_test)

In [184]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [185]:
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[ 20  23]
 [  2 109]]
0.8376623376623377


In [186]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear', random_state = 0)

In [187]:
svc.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [188]:
predict = svc.predict(X_test)

In [189]:
print(confusion_matrix(y_test, predict))
print(accuracy_score(y_test, predict))

[[ 19  24]
 [  2 109]]
0.8311688311688312


In [190]:
from sklearn.model_selection import GridSearchCV

In [191]:
parameters = [{'C':[1, 10, 100, 1000], 'kernel': ['linear']},
             {'C':[1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search1 = GridSearchCV(estimator = svc,
                          param_grid = parameters,
                          scoring='accuracy',
                          cv = 10,
                          n_jobs = -1)
grid_search1 = grid_search1.fit(X_train, y_train)

In [192]:
grid_search1.best_score_

0.8021739130434783

The best score for loan prediction was through Logistic Regression